# https://taskfile.dev

version: '3'

vars:
  OK_COLOR: '\033[32;01m'
  NO_COLOR: '\033[0m'
  LOCAL_DOCKER_COMPOSE: docker-compose.local.yml

tasks:
  help:
    desc: Show the list of commands
    cmds:
      - task --list-all

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run -c .golangci.yml

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  test:
    desc: Run tests
    cmds:
      - go test -gcflags=-l -covermode=atomic -race ./...
    env:
      ENVIRONMENT: testing

  build-api-server:
    desc: Build service
    cmds:
      - go build -buildvcs=false -ldflags="-s -w" -o bin/api-server ./cmd/server/main.go
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64

  build-api-consumer:
    desc: Build service
    cmds:
      - go build -buildvcs=false -ldflags="-s -w" -o bin/api-consumer ./cmd/consumer/main.go
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64

  local-build:
    desc: Docker compose up prometheus with our app
    cmds:
      - docker-compose -f {{.LOCAL_DOCKER_COMPOSE}} -p metrics build
      - docker-compose -f {{.LOCAL_DOCKER_COMPOSE}} -p metrics up

  local-up:
    desc: Docker compose up prometheus with our app
    cmds:
      - docker-compose -f {{.LOCAL_DOCKER_COMPOSE}} -p metrics up

  local-down:
    desc: Docker compose down prometheus with our app
    cmds:
      - docker-compose -f {{.LOCAL_DOCKER_COMPOSE}} -p metrics down

  default:
    cmds:
      - task: help